<a href="https://colab.research.google.com/github/BrnCode/Pre-processamento-completo-em-python/blob/main/Pr%C3%A9_processameto_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
import numpy as np
import pandas as pd

In [131]:
dataset = pd.read_csv("fake_data.csv") #importando dataset

In [132]:
dataset.head()

cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

In [133]:
dataset # Dataset simples com 14 linhas e 5 colunas, com variaveis numéricas faltando e variaveis categoricas.

cargo  idade  salario    bonus sócio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      NaN   1000.0   não
3       Gerente     24  15100.0      NaN   não
4       Gerente     30  35000.0   6000.0   sim
5   Programador     22   5300.0   2000.0   não
6      Analista     20      NaN   1200.0   não
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [134]:
# Separando os dados em um conjunto de atributos que serão usados como variáveis de input: 
# cargo, idade, salário e bônus e separar a variável resultante: sócio.
X = dataset.iloc[:, :-1].values # cargo, idade, salário e bônus
Y = dataset.iloc[:, 4].values # sócio

# Tratando dados faltantes

Para saber qual colunas possuem valores do tipo NaN. 

In [ ]:
dataset.isnull().sum()

cargo      0
idade      0
salario    2
bonus      2
sócio      0
dtype: int64

Obs: O registro 0 não é considerado um valor ausente.

Para substituir os valores igual 0 por NaN:

In [ ]:
dataset = dataset[['cargo', 'idade', 'salario', 'bonus', 'sócio']].replace(0,np.NAN)

## Deletando colunas

In [ ]:
#dataset.dropna(axis=1, inplace=True) 

In [ ]:
# Recomendado para tratar de colunas que não tem valores relevantes para o dataset axis = n, 
# com n = 1, 2, 3, ... para dizer que queremos deletar a coluna e inplace = True para 
# aplicarmos no dataset e não criarmos uma cópia

In [ ]:
dataset.head()

cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

## Preenchendo os valores faltantes com valores constantes

In [ ]:
dataset.fillna(0)

cargo  idade  salario    bonus sócio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      0.0   1000.0   não
3       Gerente     24  15100.0      0.0   não
4       Gerente     30  35000.0   6000.0   sim
5   Programador     22   5300.0   2000.0   não
6      Analista     20      0.0   1200.0   não
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      0.0   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

caso seja apenas uma coluna

In [ ]:
dataset['salario'].fillna(1)

0     24000.0
1      8000.0
2         1.0
3     15100.0
4     35000.0
5      5300.0
6         1.0
7     18000.0
8     38000.0
9      7300.0
10     2344.0
11     4500.0
12    30000.0
13    14000.0
Name: salario, dtype: float64

## Preenchendo valores que faltam com a média, moda e mediana dos valores da coluna 

Para substituir a coluna pela versão escolhida, basta fazer:

In [ ]:
dataset['salario'] = #Segunda linha do Média, Moda ou Mediana   

SyntaxError: ignored

#### Média

In [ ]:
media = dataset['salario'].mean()
print(media)

16795.333333333332


In [ ]:
dataset['salario'].fillna(media).head()

0    24000.000000
1     8000.000000
2    16795.333333
3    15100.000000
4    35000.000000
Name: salario, dtype: float64

In [ ]:
# dataset['salario'] = dataset['salario'].fillna(media)

In [ ]:
dataset.head()

cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

#### Moda

In [ ]:
moda = dataset['salario'].mode()
print(moda)

0      2344.0
1      4500.0
2      5300.0
3      7300.0
4      8000.0
5     14000.0
6     15100.0
7     18000.0
8     24000.0
9     30000.0
10    35000.0
11    38000.0
dtype: float64


In [ ]:
dataset['salario'].fillna(moda).head()

0    24000.0
1     8000.0
2     5300.0
3    15100.0
4    35000.0
Name: salario, dtype: float64

#### Mediana

In [ ]:
mediana = dataset['salario'].median()
print(mediana)

14550.0


In [ ]:
dataset['salario'].fillna(mediana).head()

0    24000.0
1     8000.0
2    14550.0
3    15100.0
4    35000.0
Name: salario, dtype: float64

### Preenchendo os valores que faltam com a média, moda usando o Imputer

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

vamos aplicar o método fit do imputer apenas nas colunas com dados faltantes e criando e colocando esses valores em uma coluna nova

In [ ]:
# dataset['salario2'] = imputer.fit_transform(dataset[['salario']])

In [ ]:
# dataset[['salario', 'salario2']].head()

Se “mean”, substitui os valores ausentes usando a média ao longo de cada coluna. Só pode ser usado com dados numéricos.

Se “median”, substitui os valores ausentes usando a mediana em cada coluna. Só pode ser usado com dados numéricos.

Se “most_frequent”, substitui os valores ausentes usando o valor mais frequente em cada coluna. Pode ser usado com strings ou dados numéricos.

Se “constant”, substitui os valores ausentes por fill_value. Pode ser usado com strings ou dados numéricos.

# Variaveis Categoricas

No nosso dataset temos apenas a coluna dos cargos contendo variaveis categóricas que são as variaveis nominais, sem escalas e não numéricas.

Uma ideia para tratar esse problema é utilizar a classe LabelEncoder do sklearn para transformar os nomes em números (diretor: 0, analista: 1, gerente: 2, programador: 3 e fundador: 4) 

In [ ]:
from sklearn.preprocessing import LabelEncoder

objeto do LabelEncoder e fazer fit_tranform apenas para a nossa coluna com valores categóricos:

In [ ]:
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

[[1 45 24000.0 10000.0]
 [0 22 8000.0 2000.0]
 [4 30 nan 1000.0]
 [3 24 15100.0 nan]
 [3 30 35000.0 6000.0]
 [4 22 5300.0 2000.0]
 [0 20 nan 1200.0]
 [1 50 18000.0 8000.0]
 [2 65 38000.0 28000.0]
 [0 32 7300.0 4000.0]
 [4 35 2344.0 nan]
 [4 28 4500.0 2200.0]
 [2 28 30000.0 12000.0]
 [4 30 14000.0 10000.0]]


# Reescalar Dados

Para resolver problemas com falta de escala dos dados contidos no dataset

## Normalizer

O Normalize age reescalando os dados por exemplos/linhas e não por colunas, ou seja, o Normalizer, neste caso, levará em contas os atributos idade, salário e bonus e reescalar os valores com base nesses três valores.


> ***O Normalizer é uma boa escolha quando você sabe que a distribuição dos seus dados não é normal/gaussiana ou quando você não sabe qual é o tipo de distribuição dos seus dados.***



In [135]:
from sklearn.preprocessing import Normalizer

In [136]:
dataset['salario'] = imputer.fit_transform(dataset[['salario']])
dataset['bonus'] = imputer.fit_transform(dataset[['bonus']])
dataset.head()

cargo  idade       salario    bonus sócio
0      Diretor     45  24000.000000  10000.0   sim
1     Analista     22   8000.000000   2000.0   não
2  Programador     30  16795.333333   1000.0   não
3      Gerente     24  15100.000000   7200.0   não
4      Gerente     30  35000.000000   6000.0   sim

In [138]:
X = pd.DataFrame(X)
X.head()

0   1      2      3
0      Diretor  45  24000  10000
1     Analista  22   8000   2000
2  Programador  30    NaN   1000
3      Gerente  24  15100    NaN
4      Gerente  30  35000   6000

In [140]:
X[2] = imputer.fit_transform(X[[2]])
X[3] = imputer.fit_transform(X[[3]])
X.head()

0   1             2        3
0      Diretor  45  24000.000000  10000.0
1     Analista  22   8000.000000   2000.0
2  Programador  30  16795.333333   1000.0
3      Gerente  24  15100.000000   7200.0
4      Gerente  30  35000.000000   6000.0

In [ ]:
# X_array = X.to_numpy
# print(X_array)
# print(             )
# print(type(X_array))

Preciso recortar do DataFrame só as colunas numéricas e aplicar no normalize

In [144]:
#X = X[:, 1:]
#X = pd.DataFrame({1:X[:,0], 2:X[:,1], 3:X[:,2]})
#print(X)

In [146]:
X_normalize = X.copy()
X_normalize[[1, 2, 3]] = Normalizer().fit_transform(X[[1 , 2, 3]])

In [149]:
X_normalize.head()

0         1         2         3
0      Diretor  0.001731  0.923076  0.384615
1     Analista  0.002668  0.970139  0.242535
2  Programador  0.001783  0.998231  0.059435
3      Gerente  0.001435  0.902638  0.430397
4      Gerente  0.000845  0.985622  0.168964