In [17]:
import numpy as np
import pandas as pd

In [18]:
dataset = pd.read_csv("fake_data.csv") #importando dataset

In [19]:
dataset.head()

cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

In [20]:
dataset # Dataset simples com 14 linhas e 5 colunas, com variaveis numéricas faltando e variaveis categoricas.

cargo  idade  salario    bonus sócio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      NaN   1000.0   não
3       Gerente     24  15100.0      NaN   não
4       Gerente     30  35000.0   6000.0   sim
5   Programador     22   5300.0   2000.0   não
6      Analista     20      NaN   1200.0   não
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [21]:
# Separando os dados em um conjunto de atributos que serão usados como variáveis de input: 
# cargo, idade, salário e bônus e separar a variável resultante: sócio.
X = dataset.iloc[:, :-1].values # cargo, idade, salário e bônus
Y = dataset.iloc[:, 4].values # sócio

# Tratando dados faltantes

Para saber qual colunas possuem valores do tipo NaN. 

In [22]:
dataset.isnull().sum()

cargo      0
idade      0
salario    2
bonus      2
sócio      0
dtype: int64

Obs: O registro 0 não é considerado um valor ausente.

Para substituir os valores igual 0 por NaN:

In [23]:
dataset = dataset[['cargo', 'idade', 'salario', 'bonus', 'sócio']].replace(0,np.NAN)

## Deletando colunas

In [24]:
#dataset.dropna(axis=1, inplace=True) 

In [25]:
# Recomendado para tratar de colunas que não tem valores relevantes para o dataset axis = n, 
# com n = 1, 2, 3, ... para dizer que queremos deletar a coluna e inplace = True para 
# aplicarmos no dataset e não criarmos uma cópia

In [26]:
dataset.head()

cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

## Preenchendo os valores faltantes com valores constantes

In [27]:
dataset.fillna(0)

cargo  idade  salario    bonus sócio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      0.0   1000.0   não
3       Gerente     24  15100.0      0.0   não
4       Gerente     30  35000.0   6000.0   sim
5   Programador     22   5300.0   2000.0   não
6      Analista     20      0.0   1200.0   não
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      0.0   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

caso seja apenas uma coluna

In [28]:
dataset['salario'].fillna(1)

0     24000.0
1      8000.0
2         1.0
3     15100.0
4     35000.0
5      5300.0
6         1.0
7     18000.0
8     38000.0
9      7300.0
10     2344.0
11     4500.0
12    30000.0
13    14000.0
Name: salario, dtype: float64

## Preenchendo valores que faltam com a média, moda e mediana dos valores da coluna 

Para substituir a coluna pela versão escolhida, basta fazer:

In [29]:
dataset['salario'] = #Segunda linha do Média, Moda ou Mediana   

SyntaxError: ignored

#### Média

In [30]:
media = dataset['salario'].mean()
print(media)

16795.333333333332


In [31]:
dataset['salario'].fillna(media).head()

0    24000.000000
1     8000.000000
2    16795.333333
3    15100.000000
4    35000.000000
Name: salario, dtype: float64

In [32]:
# dataset['salario'] = dataset['salario'].fillna(media)

In [33]:
dataset.head()

cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

#### Moda

In [34]:
moda = dataset['salario'].mode()
print(moda)

0      2344.0
1      4500.0
2      5300.0
3      7300.0
4      8000.0
5     14000.0
6     15100.0
7     18000.0
8     24000.0
9     30000.0
10    35000.0
11    38000.0
dtype: float64


In [35]:
dataset['salario'].fillna(moda).head()

0    24000.0
1     8000.0
2     5300.0
3    15100.0
4    35000.0
Name: salario, dtype: float64

#### Mediana

In [36]:
mediana = dataset['salario'].median()
print(mediana)

14550.0


In [37]:
dataset['salario'].fillna(mediana).head()

0    24000.0
1     8000.0
2    14550.0
3    15100.0
4    35000.0
Name: salario, dtype: float64

### Preenchendo os valores que faltam com a média, moda usando o Imputer

In [38]:
from sklearn.impute import SimpleImputer

In [39]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

vamos aplicar o método fit do imputer apenas nas colunas com dados faltantes e criando e colocando esses valores em uma coluna nova

In [40]:
# dataset['salario2'] = imputer.fit_transform(dataset[['salario']])

In [41]:
# dataset[['salario', 'salario2']].head()

Se “mean”, substitui os valores ausentes usando a média ao longo de cada coluna. Só pode ser usado com dados numéricos.

Se “median”, substitui os valores ausentes usando a mediana em cada coluna. Só pode ser usado com dados numéricos.

Se “most_frequent”, substitui os valores ausentes usando o valor mais frequente em cada coluna. Pode ser usado com strings ou dados numéricos.

Se “constant”, substitui os valores ausentes por fill_value. Pode ser usado com strings ou dados numéricos.

# Variaveis Categoricas

No nosso dataset temos apenas a coluna dos cargos contendo variaveis categóricas que são as variaveis nominais, sem escalas e não numéricas.

Uma ideia para tratar esse problema é utilizar a classe LabelEncoder do sklearn para transformar os nomes em números (diretor: 0, analista: 1, gerente: 2, programador: 3 e fundador: 4) 

In [42]:
from sklearn.preprocessing import LabelEncoder

objeto do LabelEncoder e fazer fit_tranform apenas para a nossa coluna com valores categóricos:

In [43]:
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

[[1 45 24000.0 10000.0]
 [0 22 8000.0 2000.0]
 [4 30 nan 1000.0]
 [3 24 15100.0 nan]
 [3 30 35000.0 6000.0]
 [4 22 5300.0 2000.0]
 [0 20 nan 1200.0]
 [1 50 18000.0 8000.0]
 [2 65 38000.0 28000.0]
 [0 32 7300.0 4000.0]
 [4 35 2344.0 nan]
 [4 28 4500.0 2200.0]
 [2 28 30000.0 12000.0]
 [4 30 14000.0 10000.0]]


# Reescalar Dados

Para resolver problemas com falta de escala dos dados contidos no dataset

## Normalizer

O Normalize age reescalando os dados por exemplos/linhas e não por colunas, ou seja, o Normalizer, neste caso, levará em contas os atributos idade, salário e bonus e reescalar os valores com base nesses três valores.


> ***O Normalizer é uma boa escolha quando você sabe que a distribuição dos seus dados não é normal/gaussiana ou quando você não sabe qual é o tipo de distribuição dos seus dados.***



In [44]:
from sklearn.preprocessing import Normalizer

In [45]:
dataset['salario'] = imputer.fit_transform(dataset[['salario']])
dataset['bonus'] = imputer.fit_transform(dataset[['bonus']])
dataset.head()

cargo  idade       salario    bonus sócio
0      Diretor     45  24000.000000  10000.0   sim
1     Analista     22   8000.000000   2000.0   não
2  Programador     30  16795.333333   1000.0   não
3      Gerente     24  15100.000000   7200.0   não
4      Gerente     30  35000.000000   6000.0   sim

In [46]:
X = pd.DataFrame(X)
X.head()

0   1      2      3
0  1  45  24000  10000
1  0  22   8000   2000
2  4  30    NaN   1000
3  3  24  15100    NaN
4  3  30  35000   6000

In [47]:
X[2] = imputer.fit_transform(X[[2]])
X[3] = imputer.fit_transform(X[[3]])
X.head()

0   1             2        3
0  1  45  24000.000000  10000.0
1  0  22   8000.000000   2000.0
2  4  30  16795.333333   1000.0
3  3  24  15100.000000   7200.0
4  3  30  35000.000000   6000.0

In [48]:
# X_array = X.to_numpy
# print(X_array)
# print(             )
# print(type(X_array))

Eu fiz alguma coisa que não consegui reverter direito, mas transformei o X em array e depois quando voltei pra dataset ficou sem o cabeçalho. Ai as colunas ficaram 1, 2, 3 invés de "idade", "salario", "bonus"

In [49]:
#X = X[:, 1:]
#X = pd.DataFrame({1:X[:,0], 2:X[:,1], 3:X[:,2]})
#print(X)

In [50]:
X_normalize = X.copy()
X_normalize[[1, 2, 3]] = Normalizer().fit_transform(X[[1 , 2, 3]])

In [51]:
X_normalize.head()

0         1         2         3
0  1  0.001731  0.923076  0.384615
1  0  0.002668  0.970139  0.242535
2  4  0.001783  0.998231  0.059435
3  3  0.001435  0.902638  0.430397
4  3  0.000845  0.985622  0.168964

## MinMaxScaler

Outra alternativa a reescala de dados, seu diferencial se dá uma vez que este age sobre sobre a coluna.


O cálculo da reescala é feito de forma independente entre cada coluna, de tal forma que a nova escala se dará entre 0 e 1 (ou -1 e 1 se houver valores negativos no dataset)


> ***Importante ressaltar que essa técnica funciona melhor se a distribuição dos dados não for normal e se o desvio padrão for pequeno, além disso o MinMaxScaler não reduz de forma eficaz o impacto de outliers e também preserva a distribuição original.***



valor = ( valor — Coluna.min) / (Coluna.max — Coluna.min)

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [53]:
X_minMax = X.copy()
X_minMax[[1, 2, 3]] = MinMaxScaler().fit_transform(X[[1, 2, 3]])

In [54]:
X_minMax.head()

0         1         2         3
0  1  0.555556  0.607359  0.333333
1  0  0.044444  0.158627  0.037037
2  4  0.222222  0.405299  0.000000
3  3  0.088889  0.357752  0.229630
4  3  0.222222  0.915863  0.185185

## StandardScaler

Age sobre as colunas, seu método uma vez que este subtrai do valor em questão a média da coluna e divide o resultado pelo desvio padrão. No final temos uma distribuição de dados com desvio padrão igual a 1 e variância de 1 também.

Esse método trabalha melhor em dados com distribuição normal porém vale a tentativa para outros tipos de distribuições, além disso podemos deixar como dica **que esse método resulta em ótimos frutos quando usado em conjunto com algoritmos como Linear Regression e Logistic Regression.**

In [55]:
from sklearn.preprocessing import StandardScaler

In [56]:
X_standard = X.copy()
X_standard[[1, 2, 3]] = StandardScaler().fit_transform(X[[1, 2, 3]])

In [57]:
X_standard.head()

0         1         2         3
0  1  1.002248  0.657862  0.415034
1  0 -0.907361 -0.803107 -0.770778
2  4 -0.243149  0.000000 -0.919005
3  3 -0.741308 -0.154802  0.000000
4  3 -0.243149  1.662279 -0.177872

## RobustScaler

Atua sobre as colunas e o diferencial deste método é a combinação com o uso de quartis o que nos garante um bom tratamento dos outliers.

Em seu método o RobustScaler subtrai a média do valor em questão e então divide o resultado pelo segundo quartil. 

> *Importante notar que os outliers ainda estão presentes porém estão representados dentro de uma escala em que o seu impacto negativo é reduzido.*



*valor = (valor — média) / desvio_padrão*

In [58]:
from sklearn.preprocessing import RobustScaler

In [59]:
X_robust = X.copy()
X_robust[[1, 2, 3]] = RobustScaler().fit_transform(X[[1, 2, 3]])

In [60]:
X_robust.head()

0         1         2         3
0  1  1.621622  0.535929  0.456376
1  0 -0.864865 -0.528963 -0.617450
2  4  0.000000  0.056417 -0.751678
3  3 -0.648649 -0.056417  0.080537
4  3  0.000000  1.268042 -0.080537

## QuantileTransformer

Atua sobre as colunas e também trata os outliers com uso de quartis. Este método transforma os valores de tal forma que a distribuição tende a se aproximar de uma distribuição normal.

 > *Uma observação importante é que essa tranformação pode distorcer as correlações lineares entre as colunas.*


Neste método todos os valores serão reescalados em um intervalo de 0 a 1 de tal forma que os outliers não poderão mais ser distinguidos logo ao contrário do RobustScaler o impacto da ação em cima dos outilers será grande.


In [61]:
from sklearn.preprocessing import QuantileTransformer

In [62]:
X_quantile = X.copy()
X_quantile[[1, 2, 3]] = QuantileTransformer().fit_transform(X[[1, 2, 3]])

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:2593: UserWarning: n_quantiles (1000) is greater than the total number of samples (14). n_quantiles is set to n_samples.
  "n_samples." % (self.n_quantiles, n_samples)


In [63]:
X_quantile.head()

0         1         2         3
0  1  0.846154  0.769231  0.769231
1  0  0.115385  0.307692  0.192308
2  4  0.538462  0.576923  0.000000
3  3  0.230769  0.461538  0.576923
4  3  0.538462  0.923077  0.461538

## PowerTransformer

Atua sobre as colunas e assim como o Quantile procura transformar os valores em uma distribuição mais normal, sendo indicado em situações onde uma distribuição normal é desejada para os dados, além disso esse método ainda suporta os métodos de transformação.

In [64]:
from sklearn.preprocessing import PowerTransformer

In [65]:
X_power = X.copy()
X_power[[1, 2, 3]] = PowerTransformer().fit_transform(X[[1, 2, 3]])

In [66]:
X_power.head()

0         1         2         3
0  1  1.187872  0.768685  0.775384
1  0 -1.236273 -0.711676 -0.943097
2  4  0.053928  0.222110 -1.639884
3  3 -0.828650  0.072326  0.412848
4  3  0.053928  1.428193  0.214291

# Selecionando os melhores atributos

Para entender como essa escolha é feita, ler o pdf  *Estatística para Seleção de Atributos*

Um trabalho importante é selecionar os atributos que mais fazem sentido e agregam valor em nossa solução, isso faz com que tenhamos uma melhora em alguns modelos, pela returada de ruídos das variaveis extras, além de poupar a capacidade de processamento.



> Uma dica importante é que utilizamos o SelectKBest quando temos uma noção da quantidade de atributos que temos e a quantidade de atributos que queremos, já o SelectPercentile é mais utilizado quando não temos uma noção muito clara dos números de atributos.



## SelectKBest

Para isso podemos contar com o SelectKBest do sklearn, onde o K representa o número máximo de atributos que desejamos ter em nosso dataset a ser “inputado” em nossa etapa de treino, dado o K o SelectKBest trata de encontrar os K melhores atributos a serem usados. 


*   **Importante ressaltar que aqui não existe uma melhor maneira de se escolher o valor para K a solução é tentar com diferentes valores e compararmos os resultados.**
*    **O SelectKBest não suporta dados valores negativos, portanto todos os métodos de reescala que transformam os valores em um intervalo que possui negativos devem ser descartados caso você queira aplica-lo.**







In [67]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

Em nosso exemplo irei experimentar K = 2 pois possuímos 3 atributos e irei utilizar o método de reescala MinMaxScaler. O método fit_transform já nos retorna os valores dos atributos mais importantes por tanto podemos passar a usar o retorno como o nosso novo X.

In [68]:
X_new = SelectKBest(chi2, k=2)

Nesse teste iremos usar o chi-quadrado, porém existem outros filtros. Metodo de escolha se da por:


*   **Entrada numérica; Saída numérica (modelo de Regressão):** Correlação de Pearson para relações lineares. Correlação de Spearman para correlações não lineares.


*   **Entrada numérica; Saída categórica (modelo de Classificação):** ANOVA

*   **Entrada categórica; Saída categórica (modelo de Classificação):** Chi-quadrado

Está bem definido no PDF Seleção de Variáveis (Parte 2). Entenda como utilizar o SelectKBest






In [69]:
X_new = X_new.fit_transform(X_minMax, Y)


In [73]:
X_new2 = pd.DataFrame(X_new)

In [74]:
X_new2.head()

0         1
0  0.607359  0.333333
1  0.158627  0.037037
2  0.405299         0
3  0.357752   0.22963
4  0.915863  0.185185

## SelectFromModel

A diferença do SelectFromModel se dá na forma como ele escolhe os melhores atributos, uma vez que esta escolha está atrelada a importância de um atributo para um dado modelo, além disso podemos definir um valor limite(threshold) a partir do qual passamos a considerar um atributo como importante.

Em nosso exemplo irei atrelar SelectFromModel com o classificador ExtraTreesClassifier. Ainda sobre o valor limite(threshold), podemos passar alguns valores no SelectFromModel ou não(None), caso não seja passado nada o limite utilizado por padrão será 1e-5, também podemos passar uma string “median” onde a média da importância dos atributos será o limite ou ainda podemos passar qualquer valor que desejamos.

In [75]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel

In [77]:
clf = ExtraTreesClassifier()
clf = clf.fit(X, Y)
clf.feature_importances_ #Mostra a importância de cada atributo

array([0.07224916, 0.18863602, 0.33686601, 0.40224882])

In [79]:
model = SelectFromModel(clf, prefit=True, threshold="median")
X_new = model.transform(X_minMax)

In [81]:
X_new2 = pd.DataFrame(X_new)
X_new2.head()

0         1
0  0.607359  0.333333
1  0.158627  0.037037
2  0.405299         0
3  0.357752   0.22963
4  0.915863  0.185185

## SelectPercentile

Similar ao SelectKBest, a diferença se dá que no SelectPercentile iremos passar um atributo chamado percentile que irá selecionar a porcentagem indicada dos melhores atributos, por padrão esse valor é 10

In [82]:
from sklearn.feature_selection import SelectPercentile

In [84]:
X_new = SelectPercentile(chi2, percentile=10).fit_transform(X, Y)

In [85]:
X_new

array([[24000.0],
       [8000.0],
       [16795.333333333332],
       [15100.0],
       [35000.0],
       [5300.0],
       [16795.333333333332],
       [18000.0],
       [38000.0],
       [7300.0],
       [2344.0],
       [4500.0],
       [30000.0],
       [14000.0]], dtype=object)

In [87]:
X_new.shape

(14, 1)

In [86]:
X_new2 = pd.DataFrame(X_new)
X_new2.head()

0
0    24000
1     8000
2  16795.3
3    15100
4    35000

## PCA

Podemos aplicar a técnica PCA nos atributos escolhidos, de forma grossa o PCA nada mais é que uma técnica a qual transforma atributos com uma certa correlação em um único atributo. O PCA deve ser aplicado apenas em casos em que o seu dataset possui muitas colunas, realmente um número muito grande e o treino do seu modelo acaba por ser muito demorado ou inviável devido ao alto número de colunas, uma vez que o PCA é uma técnica na qual sempre haverá perda de informações. 

Em nosso exemplo o PCA será aplicado de forma meramente ilustrativa uma vez que não possuímos muitas colunas. O atributo n_components representa quantos atributos queremos deixar, outra ideia é utilizar o parâmetro n_components="mle" dado isto Minka's MLE será utilizado para escolher a melhor dimensão a ser mantida no seu caso

In [88]:
from sklearn.decomposition import PCA

In [89]:
pca = PCA(n_components="mle")
X_new = pca.fit_transform(X_minMax)

In [90]:
X_new2 = pd.DataFrame(X_new)
X_new2.head()

0         1
0  1.297229  0.287010
1  2.270303 -0.471130
2 -1.715449 -0.105402
3 -0.719394 -0.113741
4 -0.699153  0.283764

# Separando os dados em um conjunto de treino e de teste

## Train_test_split

Irei continuar utilizando os atributos da variável X reescalados com o MinMaxScaler. Aqui iremos separar em 4 subconjuntos, X_train com as variáveis de input para treino do modelo e Y_train com os resultados de predição para treino, ambos serão utilizados mais tarde no método fit do seu modelo, X_test com as variáveis de input para test e Y_test com os resultados da predição para testes, o X_test será utilizado no método predict do seu modelo e o Y_test será utilizado para comparar com resultado retornado do seu método predict. 
O parâmetro test_size serve para indicar que o nosso conjunto de teste terá um tamanho de 20% em relação ao tamanho do dataset e o parâmetro random_state nos permite garantir que a separação dos conjuntos de teste e treino será sempre o mesmo, com a “semente” de aleatoriedade “semeada” sempre no valor indicado.

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
X_train, X_test, Y_train, Y_test = train_test_split(X_minMax, Y, test_size = 0.2, random_state = 0)

In [93]:
X_train

0         1         2         3
11  4  0.177778  0.060467  0.044444
2   4  0.222222  0.405299  0.000000
13  4  0.222222  0.326902  0.333333
9   0  0.266667  0.138995  0.111111
1   0  0.044444  0.158627  0.037037
7   1  0.666667  0.439085  0.259259
10  4  0.333333  0.000000  0.229630
3   3  0.088889  0.357752  0.229630
0   1  0.555556  0.607359  0.333333
5   4  0.044444  0.082903  0.037037
12  2  0.177778  0.775634  0.407407

In [94]:
X_test

0         1         2         3
8  2  1.000000  1.000000  1.000000
6  0  0.000000  0.405299  0.007407
4  3  0.222222  0.915863  0.185185

## KFold

O KFold facilita que possamos separar o nosso conjunto de dadas em conjunto de treinos e teste K vezes (indicado no parâmetro n_splits) e portanto fazer o treino e validar os resultados para 3 conjuntos diferentes de treino e teste. Antes precisamos colocar a nossa variável X em um formato de array.

In [95]:
X_new = X_minMax.values

In [96]:
from sklearn.model_selection import KFold

In [98]:
kf = KFold(n_splits=2)

In [99]:
time = 1
for train_index, test_index in kf.split(X_new):
    print("K = " + str(time) +  " - TRAIN:", train_index, "TEST:",  
    test_index)
    X_train, X_test = X_new[train_index], X_new[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    time += 1

K = 1 - TRAIN: [ 7  8  9 10 11 12 13] TEST: [0 1 2 3 4 5 6]
K = 2 - TRAIN: [0 1 2 3 4 5 6] TEST: [ 7  8  9 10 11 12 13]
